server:
  port: 8761
eureka:
  client:
    service-url:
      defaultZone: http://192.168.1.180:8760/eureka/
spring:
  application:
    name: service-amuse
  zipkin:
    base-url: http://192.168.1.180:9411
  datasource:
    url: jdbc:mysql://192.168.1.180:3306/db_amuse?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
    driverClassName: com.mysql.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapper/*.xml