server:
  port: 19700
eureka:
  client:
    service-url:
      defaultZone: http://192.168.1.180:8760/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
spring:
  application:
    name: service-file
  zipkin:
    base-url: http://192.168.1.182:9411
  http:
    multipart:
      enabled: true
      max-file-size: 50mb
      max-request-size: 50mb
file:
  domain: http://p5mabezxu.bkt.clouddn.com/
  rootPath: D:/playImg
  image:
    imgExtension: jpg,jpeg,png,gif,bmp
    rootPath: ${file.rootPath}/img/
    watermark: imageView2/0/q/75|watermark/2/text/546p546p56eR5oqA/font/6buR5L2T/fontsize/280/fill/IzAwMDAwMA==/dissolve/100/gravity/SouthEast/dx/10/dy/10