server:
  port: 19700
eureka:
  client:
    service-url:
      defaultZone: http://192.168.1.180:8760/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
spring:
  application:
    name: service-file
  zipkin:
    base-url: http://192.168.1.182:9411
  http:
    multipart:
      enabled: true
      max-file-size: 50mb
      max-request-size: 50mb
  mvc:
    static-path-pattern: classpath*:/static/**
file:
  domain: http://p5mabezxu.bkt.clouddn.com/
  rootPath: D:/playImg
  image:
    imgExtension: jpg,jpeg,png,gif,bmp
    rootPath: ${file.rootPath}/img/
    watermark: 