server:
  port: 8762
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8760/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
spring:
  application:
    name: service-social
  zipkin:
    base-url: http://localhost:9411
  datasource:
    url: jdbc:mysql://localhost:3306/db_social?useUnicode=true&characterEncoding=utf-8
    username: play
    password: playtech77ys90
    driverClassName: com.mysql.jdbc.Driver
  redis:
    database: 0
    host: localhost
    port: 6379
mybatis:
  mapper-locations: classpath:mapper/*.xml