server:
  port: 8762
eureka:
  client:
    service-url:
      defaultZone: http://192.168.1.180:8760/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
spring:
  zipkin:
    base-url: http://192.168.1.180:9411
  datasource:
    url: jdbc:mysql://192.168.1.180:3306/db_social?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
    driverClassName: com.mysql.jdbc.Driver
  redis:
    database: 0
    host: 192.168.1.180
    port: 6379
mybatis:
  mapper-locations: classpath:mapper/*.xml